# Generated by Django 5.1.3 on 2024-11-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_entry_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="chapter",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="entry",
            name="section",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="book, part, or section"
            ),
        ),
    ]
