# Generated by Django 5.1.3 on 2024-11-12 02:17

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0003_entry_chapter_entry_section"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ("title",)},
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="entry",
            name="section",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="entry",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="entry title"
            ),
        ),
    ]
