# Generated by Django 5.1.3 on 2024-11-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0004_alter_entry_options_alter_author_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="aka",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="commonly known as"
            ),
        ),
    ]
