# Generated by Django 5.1.3 on 2024-11-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0004_alter_book_options_book_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="visibility",
            field=models.CharField(
                choices=[("x", "Private"), ("f", "Followers"), ("p", "Public")],
                default="x",
                max_length=1,
            ),
        ),
    ]
