# Generated by Django 5.1.3 on 2024-11-12 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0005_entry_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "journal_visibility",
                    models.CharField(
                        choices=[("x", "Private"), ("f", "Followers"), ("p", "Public")],
                        default="f",
                        max_length=1,
                        verbose_name="journal visibility",
                    ),
                ),
                (
                    "default_visibility",
                    models.CharField(
                        choices=[("x", "Private"), ("f", "Followers"), ("p", "Public")],
                        default="x",
                        max_length=1,
                        verbose_name="default entry visibility",
                    ),
                ),
                ("about", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
